# Generated by Django 5.0.6 on 2024-06-22 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=120, verbose_name='题型名')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qkname', models.CharField(max_length=120, verbose_name='题库名')),
                ('creationdate', models.DateField(auto_now=True, verbose_name='修改日期')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsname', models.CharField(max_length=120, verbose_name='知识点名')),
                ('qbname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.questionbank', verbose_name='题库')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(verbose_name='题干')),
                ('torf', models.BooleanField(default=True, verbose_name='判断的对错')),
                ('option', models.JSONField(verbose_name='选项')),
                ('ans', models.TextField(verbose_name='答案')),
                ('anss', models.TextField(verbose_name='解析')),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.knowledgepoints', verbose_name='知识点')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.questionbank', verbose_name='所属题库')),
                ('typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.questiontype', verbose_name='题型')),
            ],
        ),
    ]
