# Generated by Django 5.0.6 on 2024-07-13 02:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=ckeditor.fields.RichTextField(verbose_name='题干'),
        ),
    ]
