# Generated by Django 5.0.6 on 2024-07-13 06:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_alter_question_stem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='题干'),
        ),
    ]
