# Generated by Django 5.0.6 on 2024-10-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_alter_question_stem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option',
            field=models.JSONField(null=True, verbose_name='选项'),
        ),
    ]
